# Generated by Django 3.1 on 2020-10-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_state', models.CharField(max_length=200)),
                ('time_stamp', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('start_location', models.CharField(max_length=50)),
                ('end_location', models.CharField(max_length=50)),
                ('delivery_method', models.CharField(max_length=50)),
                ('shipping_company', models.CharField(max_length=30)),
                ('temperature', models.FloatField()),
                ('quality_rating', models.FloatField()),
                ('quality_note', models.CharField(max_length=250)),
                ('qa_company', models.CharField(max_length=100)),
                ('previous_hash', models.CharField(max_length=100)),
                ('previous_item_location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=30)),
                ('producer_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('delivery_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('name', 'producer')},
            },
        ),
    ]
