# Generated by Django 3.1 on 2020-10-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResiBuyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='previous_hash',
        ),
        migrations.RemoveField(
            model_name='information',
            name='previous_item_location',
        ),
    ]
