# Generated by Django 3.1.2 on 2020-10-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResiBuyer', '0002_auto_20201008_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='block_loc',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='hash',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='hashed_text',
            field=models.CharField(default=-1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='previous_block_loc',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='previous_hash',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
