# Generated by Django 3.1.2 on 2020-10-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResiBuyer', '0003_auto_20201016_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='delivery_address',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='producer_name',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AddField(
            model_name='information',
            name='product_name',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AddField(
            model_name='information',
            name='quantity',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='information',
            name='user',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='delivery_method',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='end_location',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='location',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='previous_block_loc',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='information',
            name='previous_hash',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='qa_company',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='quality_note',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AlterField(
            model_name='information',
            name='quality_rating',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='information',
            name='shipping_company',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='information',
            name='start_location',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='temperature',
            field=models.FloatField(default=-1),
        ),
    ]
